[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "my-super-secret-token"
  organization = "iot"
  bucket = "sensor_data"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["sensor/esp32/data"]
  data_format = "json"
  json_string_fields = ["time", "device"]
  topic_tag = "topic"
  tag_keys = ["device"]
